import fs from 'node:fs';
import assert from 'node:assert/strict';

const index = fs.readFileSync('public/index.html', 'utf8');
const js = fs.readFileSync('public/companion-call-suite-v1713.js', 'utf8');
const css = fs.readFileSync('public/companion-call-suite-v1713.css', 'utf8');
const polish = fs.readFileSync('public/companion-voice-polish-v1721.css', 'utf8');

assert.match(index, /companion-call-suite-v1713\.js\?v=20260823-v17\.21-call-voice-polish/);
assert.match(index, /companion-voice-polish-v1721\.css\?v=20260823-v17\.21-call-voice-polish/);
assert.match(js, /2026-08-23-v17\.21-call-voice-polish/);
assert.match(js, /\/api\/companion\/stt/);
assert.match(js, /navigator\.mediaDevices\.getUserMedia/);
assert.match(js, /MediaRecorder/);
assert.match(js, /AudioContext|webkitAudioContext/);
assert.match(js, /getByteTimeDomainData/);
assert.match(js, /rms > \.034/);
assert.match(js, /send\.click\(\)/);
assert.match(js, /callActive/);
assert.match(js, /UnlimitedCompanionStageV1712/);
assert.match(js, /UnlimitedCompanionVoiceV1711/);
assert.match(js, /voiceApi\(\)\?\.getSettings/);
assert.match(js, /uai:companion-voice-profile/);
assert.match(js, /setAutoReadSuppressed/);
assert.match(js, /api\.speak\(cleaned/);
assert.match(js, /source:\s*"call"/);
assert.match(js, /persona:\s*settings\.persona/);
assert.match(js, /voiceId:\s*settings\.voiceId/);
assert.match(js, /playbackRate:\s*settings\.playbackRate/);
assert.match(js, /speechMode:\s*settings\.speechMode/);
assert.match(js, /emotionEnabled:\s*settings\.emotionEnabled/);
assert.match(js, /data-v1713-persona/);
assert.match(js, /function voiceSummary\(/);
assert.match(js, /声音与普通陪伴实时同步/);
assert.match(js, /data-v1713-voice-summary/);
assert.match(js, /transcribeController\?\.abort/);
assert.match(js, /generationObserver\?\.disconnect/);
assert.match(js, /attributeFilter:\s*\["disabled"\]/);
assert.match(js, /pagehide/);
assert.match(js, /visibilitychange/);
assert.match(js, /function unlockPlayback\(/);
assert.match(js, /pointerdown", unlockPlayback/);
assert.match(js, /unlockPlayback\(\);[\s\S]{0,2200}await startListening\(true\)/);

assert.doesNotMatch(js, /\/api\/companion\/tts/);
assert.doesNotMatch(js, /createBufferSource/);
assert.doesNotMatch(js, /window\.fetch\s*=/);
assert.doesNotMatch(js, /observe\(document\.body/);
assert.doesNotMatch(js, /subtree\s*:\s*true/);
assert.doesNotMatch(js, /companion-v10|companion-v11|companion-v12/);
assert.doesNotMatch(css, /\.uai-c-shell\s*\{[^}]*grid-template-columns/s);
assert.doesNotMatch(css, /\.uai-c-main\s*\{[^}]*grid-template-rows/s);
assert.match(css, /position:\s*fixed/);
assert.match(css, /prefers-reduced-motion/);
assert.match(polish, /uai-c-v1713-voice-sync/);
assert.match(polish, /data-v1713-persona/);
assert.doesNotMatch(polish, /grid-template-columns/);

console.log('V17.21 unified emotional call voice profile contract passed');